package com.bithumb.board.common.response;

public enum SuccessCode {
    BOARD_FIND_SUCCESS("BOARD FIND SUCCESS"),
    BOARD_DELETE_SUCCESS("BOARD DELETE SUCCESS"),
    BOARD_REGISTER_SUCCESS("BOARD REGISTER SUCCESS"),
    BOARD_UPDATE_SUCCESS("BOARD UPDATE SUCCESS"),
    BOARD_RECOMMEND_SUCCESS("BOARD RECOMMEND COUNTING SUCCESS"),
    COMMENT_UPDATE_SUCCESS("COMMENT UPDATE SUCCESS"),
    COMMENT_DELETE_SUCCESS("COMMENT DELETE SUCCESS"),
    COMMENT_REGISTER_SUCCESS("COMMENT REGISTER SUCCESS"),
    COMMENT_FIND_SUCCESS("COMMENT FIND SUCCESS"),

    COMMENT_RECOMMEND_SUCCESS("COMMENT_RECOMMEND_SUCCESS"),

    REPLY_UPDATE_SUCCESS("REPLY UPDATE SUCCESS"),
    REPLY_DELETE_SUCCESS("REPLY DELETE SUCCESS"),
    REPLY_REGISTER_SUCCESS("REPLY REGISTER SUCCESS"),
    REPLY_FIND_SUCCESS("REPLY FIND SUCCESS");


    private final String message;

    SuccessCode(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
