spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:5000/bithumb
    url: jdbc:mariadb://board-service.cprq7tgal4rf.us-east-1.rds.amazonaws.com:3306/bithumb
    username: admin
    password: adminrds
    sql-script-encoding: UTF-8

  profiles:
    active: dev
  application:
    name: "board-service"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    #    generate-ddl: true
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9090
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#  tomcat:
#    uri-encoding: UTF-8



