spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:5001/bithumb
    url: jdbc:mariadb://board-service-product.crtppt0lvgk7.ap-northeast-2.rds.amazonaws.com:3306/bithumb
    username: admin
    password: youngcha1008
    sql-script-encoding: UTF-8
#
  profiles:
    active: dev
  application:
    name: board

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #    generate-ddl: true
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 7000
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#  tomcat:
#    uri-encoding: UTF-8

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://3.38.23.41:6020/eureka

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: youngcha-board-service
    region:
      static: ap-northeast-2
    stack:
      auto: false